apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-client-config
  namespace: source
data:
  client.properties: |
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=PLAIN
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka-secret";
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-acl-job
  namespace: source
spec:
  template:
    spec:
      containers:
      - name: kafka-acl-creator
        image: confluentinc/cp-kafka:7.9.0
        command:
          - "/bin/sh"
          - "-c"
          - |
            kafka-acls --bootstrap-server kafka.source.svc.cluster.local:9096 --add --allow-principal User:kafka-client --operation READ --topic demo --resource-pattern-type LITERAL --command-config /tmp/client.properties && \
            kafka-acls --bootstrap-server kafka.source.svc.cluster.local:9096 --add --allow-principal User:kafka-client --operation WRITE --topic demo --resource-pattern-type LITERAL --command-config /tmp/client.properties
        volumeMounts:
        - name: kafka-client-config
          mountPath: /tmp
      restartPolicy: Never
      volumes:
      - name: kafka-client-config
        configMap:
          name: kafka-client-config
  backoffLimit: 4
